O
O O S-LOC O O O O S-PER O O O O
B-PER E-PER
S-LOC O B-LOC I-LOC E-LOC O
S-LOC O O O O O B-MISC E-MISC O O O O O O O S-LOC O O O O O O O O O
O S-LOC O O O O O O O O O O O O O O O O O O O O O S-LOC O
S-LOC O O O O O O O O O O O O O O O S-MISC O B-PER E-PER O O O O O O O O O O O O O O S-MISC O O O O O O O
B-PER E-PER O O O O O O O O O O O O O O O O O O O O O
O O S-MISC O O O O O B-MISC E-MISC O O O O O O O
O O O B-MISC E-MISC O O O O O S-LOC O O O O O O O
O O O O O O O O O O O S-LOC O O O O O O O O O O O O O O S-LOC O
B-PER E-PER O O O O O O O O O O O O B-PER E-PER O O O S-MISC O O O B-PER E-PER O O O O O O O O O O O O O
O O O O O O O S-LOC O O O O
O B-PER E-PER O O O O O O O O O O O O O O O O O O O O O O O O S-PER O O O
B-PER E-PER O O S-LOC O O O O O O O O O O O
S-LOC O O O O O S-MISC O O O O O O O O O O O S-MISC O O
S-PER O O O O O O O O
S-LOC O B-PER E-PER O O O O O S-MISC O O O O O O O
O S-MISC O O O O O O O O O O O O O O O O O O
O

